export const SET_IS_AUTH = "SET_IS_AUTH";
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const SET_UPDATED_PROFILE_DATA = "SET_UPDATED_PROFILE_DATA";

export const ADD_CONTACT = "ADD_CONTACT";